name: fmdb
description: The Fake Movie Database
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod:
  freezed_annotation:
  json_annotation: ">=4.7.0"
  http:
  google_fonts:
  go_router:

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  freezed:
  json_serializable: ">=4.7.0"
  network_image_mock:

flutter:
  uses-material-design: true
